from django.db import models
from .detalhe import Detalhe
from .documento import Documento


class DocumentoItem(models.Model):
    
    
    class Meta:
        db_table = 'docitem'  
        managed = False 
        
    iddocumentoitem = models.CharField(max_length=40, primary_key=True)
    iddetalhe = models.CharField(max_length=40, null=True, blank=True)
    idoperacao = models.CharField(max_length=40, null=True, blank=True)
    iddocumento = models.CharField(max_length=40, null=True, blank=True)
    stdocumentocancelado = models.CharField(max_length=1, null=True, blank=True)
    idpessoa = models.CharField(max_length=40, null=True, blank=True)
    tpoperacao = models.CharField(max_length=1, null=True, blank=True)
    stacerto = models.CharField(max_length=1, null=True, blank=True)
    statualizacusto = models.CharField(max_length=1, null=True, blank=True)
    qtitem = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlitem = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlcusto = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlicms = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alipi = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    idproduto = models.CharField(max_length=40, null=True, blank=True)
    vlunitario = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlmovimento = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    stexp = models.CharField(max_length=1, null=True, blank=True)
    cdexterno = models.CharField(max_length=20, null=True, blank=True)
    alicms = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    tptributo = models.CharField(max_length=1, null=True, blank=True)
    cdipi = models.CharField(max_length=20, null=True, blank=True)
    sttrib = models.CharField(max_length=3, null=True, blank=True)
    dssigla = models.CharField(max_length=5, null=True, blank=True)
    vldescontorateado = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vldesconto = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlacrescimorateado = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlacrescimo = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    cdfiscal = models.CharField(max_length=6, null=True, blank=True)
    vlsubst = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    bsicms = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    bssubst = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    ufdestino = models.CharField(max_length=2, null=True, blank=True)
    uforigem = models.CharField(max_length=2, null=True, blank=True)
    alicmsinterna = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alreducaobase = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    allucrosubst = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlsegurorateado = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlfreterateado = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vloutrosrateado = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    bsipi = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlipi = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    stprodcomissionado = models.BooleanField(null=True, blank=True)
    stvendaespecial = models.CharField(max_length=1, null=True, blank=True)
    alacrescimo = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    aldesconto = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlunitariooriginal = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    cdempvend = models.CharField(max_length=3, null=True, blank=True)
    cdempresa = models.CharField(max_length=3, null=True, blank=True)
    dtreferencia = models.DateTimeField(null=True, blank=True)
    qtvolumes = models.IntegerField(null=True, blank=True)
    tpdevolucao = models.CharField(max_length=1, null=True, blank=True)
    bsiss = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    aliss = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alpis = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alcofins = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    qtdevolvida = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlconhecimentorateado = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlpisret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlcofinsret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlinssret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlirret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlcsllret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    naturezaoperacao = models.IntegerField(null=True, blank=True)
    alpisret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alcofinsret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alinssret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alirret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alcsllret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlbasecsrf = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlbaseinssret = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlbaseirrf = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlmaterialservico = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    cdsittribcofins = models.CharField(max_length=2, null=True, blank=True)
    cdsittribpis = models.CharField(max_length=2, null=True, blank=True)
    stmovimentacaofisica = models.CharField(max_length=1, null=True, blank=True)
    vlbasepis = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlbasecofins = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlpis = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlcofins = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    gtin = models.CharField(max_length=14, null=True, blank=True)
    vlfcpicms = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    bsfcpsubst = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlfcpsubst = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    bsfcpicms = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    alfcp = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vldificms = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    vlreducaobaseicms = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.iddocumentoitem
    