from django.db import models

class Produto(models.Model):

    class Meta:
        db_table = 'produto'  
        managed = False 

    idproduto = models.CharField(max_length=40, primary_key=True)
    cdchamada = models.CharField(max_length=15, blank=True, null=True)
    idgradev = models.CharField(max_length=40, blank=True, null=True)
    idgradeh = models.CharField(max_length=40, blank=True, null=True)
    idunidade = models.CharField(max_length=40, blank=True, null=True)
    cdtratamentoespecial = models.CharField(max_length=2, blank=True, null=True)
    nmproduto = models.CharField(max_length=50, blank=True, null=True)
    stativo = models.CharField(max_length=1, blank=True, null=True)
    idgrupo = models.CharField(max_length=40, blank=True, null=True)
    dsobservacao = models.TextField(blank=True, null=True)
    vlcusto = models.FloatField(blank=True, null=True)
    vlpreco = models.FloatField(blank=True, null=True)
    alicmsvenda = models.FloatField(blank=True, null=True)
    alipivenda = models.FloatField(blank=True, null=True)
    tributacao = models.CharField(max_length=1, blank=True, null=True)
    stexp = models.CharField(max_length=1, blank=True, null=True)
    cdexterno = models.CharField(max_length=20, blank=True, null=True)
    cdipi = models.CharField(max_length=20, blank=True, null=True)
    cdsittrib = models.CharField(max_length=3, blank=True, null=True)
    stcestabasica = models.BooleanField(blank=True, null=True)
    nrdiasreposicao = models.IntegerField(blank=True, null=True)
    stabate = models.BooleanField(blank=True, null=True)
    stcombustivel = models.BooleanField(blank=True, null=True)
    idfornecprincipal = models.CharField(max_length=40, blank=True, null=True)
    idcalculoicms = models.CharField(max_length=40, blank=True, null=True)
    stalicmsinterna2 = models.CharField(max_length=1, blank=True, null=True)
    dtalttemporeposicao = models.DateTimeField(blank=True, null=True)
    dtaltalicmsvenda = models.DateTimeField(blank=True, null=True)
    cdclassfiscal = models.CharField(max_length=2, blank=True, null=True)
    stprecounico = models.BooleanField(blank=True, null=True)
    dtaltalipivenda = models.DateTimeField(blank=True, null=True)
    alroyaties = models.FloatField(blank=True, null=True)
    cdsittribjuridica = models.CharField(max_length=3, blank=True, null=True)
    ippt = models.CharField(max_length=10, blank=True, null=True)
    iat = models.CharField(max_length=10, blank=True, null=True)
    cdlistaservicolc = models.IntegerField(blank=True, null=True)
    cdsttribipientrada = models.CharField(max_length=2, blank=True, null=True)
    cdsttribipisaida = models.CharField(max_length=2, blank=True, null=True)
    cdgenero = models.CharField(max_length=2, blank=True, null=True)
    tipoitem = models.CharField(max_length=2, blank=True, null=True)
    alretencaoinss = models.FloatField(blank=True, null=True)
    alretencaoirrf = models.FloatField(blank=True, null=True)
    alretencaocsll = models.FloatField(blank=True, null=True)
    alretencaopis = models.FloatField(blank=True, null=True)
    alretencaocofins = models.FloatField(blank=True, null=True)
    idpautafiscal = models.CharField(max_length=40, blank=True, null=True)
    stfotounicacoluna = models.BooleanField(blank=True, null=True)
    stfotounicalinha = models.BooleanField(blank=True, null=True)
    idpadrao = models.CharField(max_length=40, blank=True, null=True)
    cest = models.CharField(max_length=7, blank=True, null=True)
    stecommerce = models.BooleanField(blank=True, null=True)
    tpformatoemabalagem = models.IntegerField(blank=True, null=True)
    vllargura = models.FloatField(blank=True, null=True)
    vlaltura = models.FloatField(blank=True, null=True)
    vlcomprimento = models.FloatField(blank=True, null=True)
    dsdescricaoecommerce = models.TextField(blank=True, null=True)
    idcategoria = models.CharField(max_length=40, blank=True, null=True)
    idmarca = models.CharField(max_length=40, blank=True, null=True)
    tpproduto = models.IntegerField(blank=True, null=True)
    stisentotaxaservico = models.BooleanField(blank=True, null=True)
    tptaxa = models.IntegerField(blank=True, null=True)
    stadicional = models.BooleanField(blank=True, null=True)
    stautoatendimento = models.BooleanField(blank=True, null=True)
    stcdfiscalalternativo = models.BooleanField(blank=True, null=True)
    qtminimavenda = models.FloatField(blank=True, null=True)
    qtmaximavenda = models.FloatField(blank=True, null=True)
    fracaounidade = models.FloatField(blank=True, null=True)
    idadicionaltipo = models.CharField(max_length=40, blank=True, null=True)
    tpespecialidade = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.nmproduto
