# Generated by Django 5.0.1 on 2024-01-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('iddetalhe', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('cdprincipal', models.CharField(max_length=20, unique=True)),
                ('dsdetalhe', models.CharField(max_length=40)),
                ('imagem', models.ImageField(null=True, upload_to='produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('idcomissao', models.AutoField(primary_key=True, serialize=False)),
                ('iddocumento', models.CharField(max_length=20, unique=True)),
                ('iddocumentoitem', models.CharField(max_length=20, unique=True)),
                ('cdorcamento', models.CharField(max_length=20, unique=True)),
                ('cdchamada', models.CharField(max_length=20)),
                ('dsvendedor', models.CharField(max_length=80)),
                ('vltotal', models.FloatField()),
                ('ispaid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdprincipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expiration_control.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Validade',
            fields=[
                ('idvalidade', models.AutoField(primary_key=True, serialize=False)),
                ('dtvalidade', models.DateField()),
                ('qtestoque', models.IntegerField()),
                ('stativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdprincipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expiration_control.produto')),
            ],
        ),
    ]
