# Generated by Django 5.0.1 on 2024-01-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiration_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validade',
            old_name='cdprincipal',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='expiration_control/static/produtos'),
        ),
    ]
