# Generated by Django 4.0 on 2024-01-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expiration_control', '0007_altedatadocs_alterdatadocprods_alterdataprods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AltedataDocs',
            new_name='AlterdataDocs',
        ),
    ]
