# Generated by Django 4.0 on 2024-02-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiration_control', '0011_alter_comissao_cdorcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='iddocumento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='iddocumentoitem',
            field=models.CharField(max_length=40),
        ),
    ]
